baseURL = 'https://manchey.github.io/'
languageCode = 'en-us'
title = 'Manchey Blog'
theme = "hugo-book"
pagination.pagerSize = 2
Copyright = "© Manchey Lee 2024"
description = "Manchey's personal blog about technology and life"
googleAnalytics = "G-4T451VBM9P"

# 这个设置会将所有 URL 转换为规范的绝对路径
canonifyurls = true
# 可以在模板中使用 .GitInfo 变量显示这些信息
enableGitInfo = true
# 自动生成 robots.txt 文件
enableRobotsTXT = true


[params]
  BookTheme = 'light'
  BookToC = true
  BookFavicon = "logo.png"
  BookLogo = "logo.png"
  BookRepo = ""
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
  BookSection = "content"

[menu]
  [[menu.after]]
    name = "Github"
    url = "https://github.com/Manchey/manchey.github.io"
    weight = 50

[permalinks]
  post = "/posts/:year/:month/:slug/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "perldoc"
    anchorLineNos = true # 行号是否可点击

